apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089
    name: web
  - port: 5557
    targetPort: 5557
    name: master
  selector:
    app: locust-master

