# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/hello.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'src/proto/hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15src/proto/hello.proto\x12\x06vector\"\x1b\n\rVectorRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x0eVectorResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"2\n\x13InsertVectorRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"\'\n\x14InsertVectorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x15GetVectorByKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x13InsertSampleRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x14InsertSampleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xaa\x02\n\rVectorService\x12:\n\tGetVector\x12\x15.vector.VectorRequest\x1a\x16.vector.VectorResponse\x12I\n\x0cInsertVector\x12\x1b.vector.InsertVectorRequest\x1a\x1c.vector.InsertVectorResponse\x12G\n\x0eGetVectorByKey\x12\x1d.vector.GetVectorByKeyRequest\x1a\x16.vector.VectorResponse\x12I\n\x0cInsertSample\x12\x1b.vector.InsertSampleRequest\x1a\x1c.vector.InsertSampleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORREQUEST']._serialized_start=33
  _globals['_VECTORREQUEST']._serialized_end=60
  _globals['_VECTORRESPONSE']._serialized_start=62
  _globals['_VECTORRESPONSE']._serialized_end=106
  _globals['_INSERTVECTORREQUEST']._serialized_start=108
  _globals['_INSERTVECTORREQUEST']._serialized_end=158
  _globals['_INSERTVECTORRESPONSE']._serialized_start=160
  _globals['_INSERTVECTORRESPONSE']._serialized_end=199
  _globals['_GETVECTORBYKEYREQUEST']._serialized_start=201
  _globals['_GETVECTORBYKEYREQUEST']._serialized_end=237
  _globals['_INSERTSAMPLEREQUEST']._serialized_start=239
  _globals['_INSERTSAMPLEREQUEST']._serialized_end=272
  _globals['_INSERTSAMPLERESPONSE']._serialized_start=274
  _globals['_INSERTSAMPLERESPONSE']._serialized_end=313
  _globals['_VECTORSERVICE']._serialized_start=316
  _globals['_VECTORSERVICE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
